### ISSUE TITLE
Can you add a README?

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [TimothyMeadows/nodecrack-ng#1]
Hey I'm interested in your project... could you add a README?

**Comment by TimothyMeadows** [comment]
Sorry for the delay been busy :(. What are you looking for explained specifically? This was written in haste for a demo i had to do last year.

**Comment by jduncan8142** [comment]
Can you please explain how the setup works and how to run the cracking process.

**Comment by TimothyMeadows** [comment]
This projects purpose was simply to serve as a portable demo for distributed computing on the Raspberry PI. It's on github so attendees could see code if they wanted. I did add a basic README but it should be clear i do not support this project it was just a demo. Feel free to fork it and use it how you wish beyond breaking local laws in your area. That not be advisable.
